# Generated by Django 5.0.7 on 2026-09-20 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crsc_calls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directcall",
            name="engineer_contact_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact Number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
