# Generated by Django 5.0.7 on 2026-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crsc_calls", "0002_alter_directcall_engineer_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="directcall",
            name="assigned_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Assigned Date"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="customer_feedback",
            field=models.TextField(
                blank=True, null=True, verbose_name="Customer Feedback"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="feedback_submission_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Feedback Submission Datetime"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="final_action_taken",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Final Action Taken"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="issue_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Issue Description"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="rating",
            field=models.IntegerField(blank=True, null=True, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="device_to_be_sent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Please Select"),
                    ("Goa", "Goa"),
                    ("Hyderabad", "Hyderabad"),
                    ("Chennai", "Chennai"),
                ],
                max_length=50,
                null=True,
                verbose_name="Faulty Device Sent to Location",
            ),
        ),
    ]
