# Generated by Django 4.2.13 on 2026-09-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crsc_calls", "0003_directcall_assigned_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directcall",
            name="responsibility",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Responsibility"
            ),
        ),
    ]
