# Generated by Django 5.0.7 on 2026-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crsc_calls", "0006_backfill_responsibility_ialert_to_al"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directcall",
            name="al_updated_contact_no",
            field=models.TextField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="AL Updated Contact No",
            ),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="customer_feedback",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Customer Feedback"
            ),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="dealer_address",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="external_modification",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="follow_up_comment",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Follow-Up Comment"
            ),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="hod_comment",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="HOD Comment"
            ),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="issue_category",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="issue_description",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Issue Description"
            ),
        ),
        migrations.AlterField(
            model_name="directcall",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
