# Generated by Django 5.0.7 on 2026-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crsc_calls", "0009_reformat_directcall_tat_hhmmss"),
    ]

    operations = [
        migrations.AddField(
            model_name="directcall",
            name="darby_lookup_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Darby Lookup Time"
            ),
        ),
        migrations.AddField(
            model_name="directcall",
            name="darby_lookup_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="pending / success / not_found / failed",
                max_length=20,
                null=True,
                verbose_name="Darby Lookup Status",
            ),
        ),
    ]
