# Generated by Django 5.0.7 on 2026-09-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('item_sub_category', models.CharField(max_length=100)),
                ('part_sub_category', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('customer_code', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst', models.CharField(max_length=10)),
                ('freight_scope', models.CharField(max_length=100)),
                ('freight_scope_value', models.CharField(max_length=100)),
                ('transporter_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('contact_mail_id', models.EmailField(max_length=254)),
                ('engineer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('part_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('item_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_value_without_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_invoice_value_with_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credited_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('gap', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('theoretical_payment_due_date', models.DateField(blank=True, null=True)),
                ('grn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_grn_delivery_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received')], max_length=100, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('docket_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_shipment', models.DateField(blank=True, null=True)),
                ('due_emails', models.TextField(blank=True, null=True)),
                ('shipment_emails', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gst', models.CharField(blank=True, max_length=10, null=True)),
                ('freight_scope', models.CharField(blank=True, max_length=100, null=True)),
                ('freight_scope_value', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('engineer', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.orderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=150)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='billing.billingdata')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['unique_id'], name='billing_bil_unique__f2fd53_idx'), models.Index(fields=['-changed_at'], name='billing_bil_changed_6b02a9_idx')],
            },
        ),
    ]
