# Generated by Django 5.0.7 on 2026-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdata",
            name="upload_invoice",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="billing_invoices/",
                verbose_name="Upload Invoice",
            ),
        ),
    ]
