# Generated by Django 4.2.13 on 2026-09-20 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIS140_FLOW", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ais140request",
            name="icicid_no",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{20}$", "ICCID No must be exactly 20 digits."
                    )
                ],
                verbose_name="ICCID No",
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="imei_no",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{15}$", "IMEI No must be exactly 15 digits."
                    )
                ],
                verbose_name="IMEI No",
            ),
        ),
    ]
