# Generated by Django 5.0.7 on 2026-09-20 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIS140_FLOW", "0002_alter_ais140request_icicid_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ais140request",
            name="Customer_Alternate_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
                verbose_name="Cust Alt Contact No",
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="Customer_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="Dealer_Contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
                verbose_name="Customer Phone",
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="owner_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="psn",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "PSN No must be exactly 10 digits."
                    )
                ],
                verbose_name="PSN No",
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="requested_phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
                verbose_name="Requestor Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="ais140request",
            name="vin_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{17}$",
                        "Chassis No (VIN) must be exactly 17 alphanumeric characters.",
                    )
                ],
                verbose_name="Chassis No",
            ),
        ),
    ]
