# Generated by Django 5.0.7 on 2026-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIS140_FLOW", "0004_backfill_responsibility_dtil_to_danlaw"),
    ]

    operations = [
        migrations.AddField(
            model_name="ais140request",
            name="sos_fitment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="SOS Fitment Date"
            ),
        ),
    ]
