# Generated by Django 5.0.7 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIS140_FLOW", "0005_ais140request_sos_fitment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ais140request",
            name="Update_to_AL_API",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remark", "Remark"),
                    ("Temporary", "Temporary"),
                    ("Permanent", "Permanent"),
                ],
                default="",
                max_length=250,
                null=True,
                verbose_name="Update to AL API",
            ),
        ),
    ]
